# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-18 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentvote',
            name='vote_type',
            field=models.IntegerField(choices=[(1, 'UP'), (-1, 'DOWN')]),
        ),
        migrations.AlterField(
            model_name='postvote',
            name='vote_type',
            field=models.IntegerField(choices=[(1, 'UP'), (-1, 'DOWN')]),
        ),
    ]
